CREATE TABLE post_attachments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id            BIGINT                                  NOT NULL,
    original_file_name VARCHAR(255),
    stored_file_name   VARCHAR(255),
    content_type       VARCHAR(255),
    size               BIGINT,
    url                VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_post_attachments PRIMARY KEY (id)
);

ALTER TABLE post_attachments
    ADD CONSTRAINT FK_POST_ATTACHMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);
